#!/usr/bin/env bash

## Update the database from Pantheon for a Docksal powered local site.
##
## Usage: fin downloaddb

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT is passed from fin.
# The following variables are configured in the '.env' file: DOCROOT, VIRTUAL_HOST.

SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

#-------------------------- END: Settings --------------------------------

#-------------------------- Include functions --------------------------------

source "${PROJECT_ROOT}/.docksal/commands/common/import_database.sh"
source "${PROJECT_ROOT}/.docksal/commands/common/enable_modules.sh"

#-------------------------- END: Include functions --------------------------------

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

is_windows ()
{
	local res=$(uname | grep 'CYGWIN_NT')
	if [[ "$res" != "" ]]; then
		return 0
	else
		return 1
	fi
}

#-------------------------- END: Helper functions --------------------------------


#-------------------------- Execution --------------------------------


# Import database.
echo -e "${green_bg} Step 1 of 2 ${NC}${green} Importing database...${NC}"
time import_database

# Configure things for local development environment.
echo -e "${green_bg} Step 2 of 2 ${NC}${green} Enabling local development-related modules...${NC}"
time enable_modules

#-------------------------- END: Execution --------------------------------